---
kind: pipeline
type: kubernetes
name: code-analysis
environment:
  PROJECT_KEY: consumer-abe-atreel-user-message
trigger:
  branch:
  - master
  - development
  event:
  - pull_request
steps:
- name: dependency-check
  image: owasp/dependency-check
  commands:
  - sed -i -e "s/PROJECT_VERSION/${DRONE_COMMIT_SHA:0:8}/g" sonar-project.properties
  - /usr/share/dependency-check/bin/dependency-check.sh -s . -f JSON -f HTML -f XML --enableExperimental --go .

---
kind: pipeline
type: docker
name: development
steps:
- name: build
  image: plugins/docker
  settings:
    repo: occmundial/consumer-abe-atreel-user-message
    tags: ${DRONE_COMMIT_SHA:0:8}
    username:
      from_secret: docker_devops_user
    password:
      from_secret: docker_devops_password
    dockerfile: Dockerfile
    build_args:
      - ENV=dev
      - VERSION=${DRONE_COMMIT_SHA:0:8}


  - name: push to gitops
    image: alpine/git
    commands:
      - apk update && apk --no-cache add bash curl
      - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
      - cp kustomize /usr/local/bin/kustomize
      - git clone -b main https://github.com/occmundial/gitops-occ.git
      - cd gitops-occ/Atreel/consumer-abe-atreel-user-message/overlays/development
      - /usr/local/bin/kustomize edit set image occmundial/consumer-abe-atreel-user-message:${DRONE_COMMIT_SHA:0:8}
      - git config --local user.name "Drone"
      - git config --local user.email "devops@occ.com.mx"
      - git commit -a -m " Atreel/consumer-abe-atreel-user-message new version ${DRONE_COMMIT_SHA:0:8}"
      - git push origin main
trigger:
  branch:
    - development
    - feat/ci
  event:
    - push

---
kind: pipeline
type: kubernetes
name: production
steps:
  - name: build
    image: plugins/docker
    settings:
      repo: occmundial/consumer-abe-atreel-user-message
      tags: ${DRONE_COMMIT_SHA:0:8}
      username:
        from_secret: docker_devops_user
      password:
        from_secret: docker_devops_password
      dockerfile: Dockerfile
      build_args:
        - env=prod
        - version=${DRONE_COMMIT_SHA:0:8}

  - name: push consumer-abe-atreel-user-message to gitops
    image: alpine/git
    commands:
      - apk update && apk --no-cache add bash curl
      - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
      - cp kustomize /usr/local/bin/kustomize
      - git clone -b main https://github.com/occmundial/gitops-occ.git
      - cd gitops-occ/Atreel/consumer-abe-atreel-user-message/overlays/production
      - /usr/local/bin/kustomize edit set image occmundial/consumer-abe-atreel-user-message:${DRONE_COMMIT_SHA:0:8}
      - git config --local user.name "Drone"
      - git config --local user.email "devops@occ.com.mx"
      - git commit -a -m " Atreel/consumer-abe-atreel-user-message new version ${DRONE_COMMIT_SHA:08}"
      - git push origin main 

trigger:
  branch:
    - main
  event:
    - push



---
kind: pipeline
name: notify
steps:
- name: notify-notify
  image: plugins/slack-blame
  settings:
    token: 
      from_secret: token_notify
    channel: ci-candidate-notifications
    failure_template: |
        ❌ *Project:* <${CI_REPO_LINK}|${DRONE_REPO}>  *Build* *{{ uppercasefirst build.status }}:* #{{ build.number }}
        *Commit:* <${CI_REPO_LINK}/commit/{{ build.commit }}|{{ truncate build.commit 7 }}> *Branch:* <${CI_REPO_LINK}/commits/${DRONE_SOURCE_BRANCH}|${DRONE_SOURCE_BRANCH}> *Author:* ${DRONE_COMMIT_AUTHOR}
        <${DRONE_BUILD_LINK}|Visit build page >  
trigger:
  branch:
    - main
    - development
  event:
    - push 
  status:
    - failure
depends_on:
  - development
  - production